# Generated by Django 4.2.4 on 2024-02-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firebase_uid",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("level", models.IntegerField(default=0)),
                ("book", models.IntegerField(default=0)),
                ("course", models.IntegerField(default=0)),
                ("mosabaka", models.IntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["score"],
            },
        ),
    ]
