# Generated by Django 4.2.4 on 2024-02-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_student_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="book",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
