# Generated by Django 4.2.4 on 2024-02-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_student_book_alter_student_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="book",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="student",
            name="mosabaka",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="student",
            name="score",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
