# Generated by Django 4.2.4 on 2024-02-24 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_student_book_alter_student_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="birthday",
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
