# Generated by Django 4.2.4 on 2024-03-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_student_birthday_student_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="country",
            field=models.CharField(default="Algeria", max_length=255),
        ),
    ]
