# Generated by Django 4.2.4 on 2024-03-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_student_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="city",
            field=models.CharField(default="الجزائر", max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="country",
            field=models.CharField(default="الجزائر", max_length=255),
        ),
    ]
