# Generated by Django 4.2.4 on 2024-03-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_student_city_alter_student_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
