# Generated by Django 4.1.3 on 2023-08-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tag',
            field=models.CharField(default='', max_length=255),
        ),
    ]
