# Generated by Django 4.2.4 on 2023-08-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0010_candidate_book_book_url_book_locked_quiz_to_save_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["book_order"],
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={
                "ordering": ["id"],
                "verbose_name": "quiz",
                "verbose_name_plural": "Quizzes",
            },
        ),
        migrations.RemoveField(
            model_name="book",
            name="image",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="book",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="level",
        ),
        migrations.AddField(
            model_name="book",
            name="book_order",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="LockedQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="New Quiz", max_length=255, verbose_name="Quiz Title"
                    ),
                ),
                ("locked", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="quizzes.book",
                    ),
                ),
                (
                    "level",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="quizzes.level",
                    ),
                ),
            ],
            options={
                "verbose_name": "LockedQuiz",
                "verbose_name_plural": "LockedQuizzes",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="lockedQuiz",
            field=models.ManyToManyField(
                related_name="question", to="quizzes.lockedquiz"
            ),
        ),
    ]
