# Generated by Django 4.2.4 on 2023-08-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0011_alter_book_options_alter_quiz_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lockedquiz",
            name="course",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="quiz",
                to="quizzes.course",
            ),
        ),
        migrations.AlterField(
            model_name="lockedquiz",
            name="book",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="quiz",
                to="quizzes.book",
            ),
        ),
        migrations.AlterField(
            model_name="lockedquiz",
            name="level",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="quiz",
                to="quizzes.level",
            ),
        ),
    ]
