# Generated by Django 4.2.4 on 2023-08-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0012_lockedquiz_course_alter_lockedquiz_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="lockedQuiz",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="question", to="quizzes.lockedquiz"
            ),
        ),
    ]
