# Generated by Django 4.2.4 on 2023-08-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0014_alter_question_lockedquiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
