# Generated by Django 4.2.4 on 2023-08-25 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0015_course_course_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="book",
                to="quizzes.level",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="course",
                to="quizzes.book",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="lockedQuiz",
            field=models.ManyToManyField(
                related_name="question", to="quizzes.lockedquiz"
            ),
        ),
    ]
