# Generated by Django 4.2.4 on 2023-08-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0016_alter_book_level_alter_course_book_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["course_order"],
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="level",
            options={
                "ordering": ["level_order"],
                "verbose_name": "Level",
                "verbose_name_plural": "Levels",
            },
        ),
        migrations.AddField(
            model_name="level",
            name="level_order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
