# Generated by Django 4.2.4 on 2023-08-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0017_alter_course_options_alter_level_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book",
                to="quizzes.level",
            ),
        ),
    ]
