# Generated by Django 4.2.4 on 2023-08-27 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0020_alter_lockedquiz_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book",
                to="quizzes.level",
            ),
        ),
        migrations.AlterField(
            model_name="lockedquiz",
            name="level",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz",
                to="quizzes.level",
            ),
        ),
    ]
