# Generated by Django 4.2.4 on 2023-08-28 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0021_alter_book_level_alter_lockedquiz_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Quiz Title")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "BookQuiz",
                "verbose_name_plural": "BooksQuizzes",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CourseQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Quiz Title")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "CourseQuiz",
                "verbose_name_plural": "CoursesQuizzes",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="LevelQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Quiz Title")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "LevelQuiz",
                "verbose_name_plural": "LevelsQuizzes",
                "ordering": ["id"],
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["id"],
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="level",
            options={
                "ordering": ["id"],
                "verbose_name": "Level",
                "verbose_name_plural": "Levels",
            },
        ),
        migrations.RemoveField(
            model_name="question",
            name="lockedQuiz",
        ),
        migrations.AlterField(
            model_name="book",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="book",
                to="quizzes.level",
            ),
        ),
        migrations.DeleteModel(
            name="LockedQuiz",
        ),
        migrations.AddField(
            model_name="levelquiz",
            name="level",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="quiz",
                to="quizzes.level",
            ),
        ),
        migrations.AddField(
            model_name="coursequiz",
            name="course",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="quiz",
                to="quizzes.course",
            ),
        ),
        migrations.AddField(
            model_name="bookquiz",
            name="book",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="quiz",
                to="quizzes.book",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="bookQuiz",
            field=models.ManyToManyField(
                related_name="question", to="quizzes.bookquiz"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="courseQuiz",
            field=models.ManyToManyField(
                related_name="question", to="quizzes.coursequiz"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="levelQuiz",
            field=models.ManyToManyField(
                related_name="question", to="quizzes.levelquiz"
            ),
        ),
    ]
