# Generated by Django 4.2.4 on 2023-08-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0022_bookquiz_coursequiz_levelquiz_alter_course_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="num_pass_book",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="num_pass_course",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="level",
            name="num_pass_level",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
