# Generated by Django 4.2.4 on 2023-08-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0025_remove_book_locked_remove_course_watched_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="bookQuiz",
            field=models.ManyToManyField(
                related_name="question", to="quizzes.bookquiz"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="courseQuiz",
            field=models.ManyToManyField(
                related_name="question", to="quizzes.coursequiz"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="levelQuiz",
            field=models.ManyToManyField(
                related_name="question", to="quizzes.levelquiz"
            ),
        ),
    ]
