# Generated by Django 4.2.4 on 2023-08-30 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0026_alter_question_bookquiz_alter_question_coursequiz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="bookQuiz",
            field=models.ManyToManyField(
                blank=True, related_name="question", to="quizzes.bookquiz"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="courseQuiz",
            field=models.ManyToManyField(
                blank=True, related_name="question", to="quizzes.coursequiz"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="levelQuiz",
            field=models.ManyToManyField(
                blank=True, related_name="question", to="quizzes.levelquiz"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question",
                to="quizzes.quiz",
            ),
        ),
    ]
