# Generated by Django 4.2.4 on 2023-08-30 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0027_alter_question_bookquiz_alter_question_coursequiz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question",
                to="quizzes.quiz",
            ),
        ),
    ]
