# Generated by Django 4.2.4 on 2023-08-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0028_alter_question_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="level_pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
    ]
