# Generated by Django 4.2.4 on 2023-08-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0029_level_level_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="level_pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/level/"),
        ),
    ]
