# Generated by Django 4.2.4 on 2023-08-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0030_alter_level_level_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/book/"),
        ),
    ]
