# Generated by Django 4.2.4 on 2024-01-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0031_book_book_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
