# Generated by Django 4.2.4 on 2024-02-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0033_quizscore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizscore",
            name="quiz",
        ),
        migrations.AddField(
            model_name="quizscore",
            name="quiz_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizzes.bookquiz",
            ),
        ),
        migrations.AddField(
            model_name="quizscore",
            name="quiz_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizzes.coursequiz",
            ),
        ),
        migrations.AddField(
            model_name="quizscore",
            name="quiz_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizzes.levelquiz",
            ),
        ),
        migrations.AddField(
            model_name="quizscore",
            name="quiz_type",
            field=models.CharField(
                choices=[("book", "Book"), ("course", "Course"), ("level", "Level")],
                default="course",
                max_length=10,
            ),
        ),
    ]
