# Generated by Django 4.2.4 on 2024-03-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0034_remove_quizscore_quiz_quizscore_quiz_book_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mosabaka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Mosabka Title"),
                ),
                ("mosabaka_order", models.IntegerField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Active Status"),
                ),
            ],
            options={
                "verbose_name": "Mosabaka",
                "verbose_name_plural": "Mosabakat",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="Mosabaka",
            field=models.ManyToManyField(
                blank=True, related_name="question", to="quizzes.mosabaka"
            ),
        ),
    ]
