# Generated by Django 4.2.4 on 2024-03-02 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_student_birthday_student_city"),
        ("quizzes", "0035_mosabaka_question_mosabaka"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizscore",
            name="quiz_level",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizzes.levelquiz",
            ),
        ),
        migrations.CreateModel(
            name="MosabakaScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                (
                    "Mosabaka",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mosabakScore",
                        to="quizzes.mosabaka",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.student"
                    ),
                ),
            ],
        ),
    ]
