# Generated by Django 4.2.4 on 2024-03-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0036_alter_quizscore_quiz_level_mosabakascore"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mosabakascore",
            old_name="Mosabaka",
            new_name="mosabaka",
        ),
    ]
