# Generated by Django 4.2.4 on 2024-03-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0037_rename_mosabaka_mosabakascore_mosabaka"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mosabakascore",
            name="mosabaka",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizzes.mosabaka",
            ),
        ),
    ]
