# Generated by Django 4.2.4 on 2024-03-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_student_birthday_student_city"),
        ("quizzes", "0039_rename_mosabaka_question_mosabaka"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mosabakascore",
            name="mosabaka",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizzes.mosabaka",
            ),
        ),
        migrations.AlterField(
            model_name="mosabakascore",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.student"
            ),
        ),
    ]
