# Generated by Django 4.2.4 on 2024-03-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0040_alter_mosabakascore_mosabaka_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Active Status"),
        ),
    ]
