# Generated by Django 4.2.4 on 2024-03-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0041_book_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizscore",
            name="quiz_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizzes.levelquiz",
            ),
        ),
    ]
