# Generated by Django 4.2.4 on 2024-03-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0042_alter_quizscore_quiz_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="book_url",
        ),
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, upload_to="books"),
        ),
    ]
