# Generated by Django 4.2.4 on 2024-03-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0043_remove_book_book_url_book_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="mosabaka",
            name="ready",
            field=models.BooleanField(default=False),
        ),
    ]
