# Generated by Django 4.2.4 on 2024-03-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0044_mosabaka_ready"),
    ]

    operations = [
        migrations.AddField(
            model_name="mosabaka",
            name="book_pdf",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/mosabakat/"),
        ),
        migrations.AddField(
            model_name="mosabaka",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
