# Generated by Django 4.2.4 on 2024-03-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0047_book_is_last_course_is_last_level_is_last"),
    ]

    operations = [
        migrations.AddField(
            model_name="mosabaka",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
