# Generated by Django 4.2.4 on 2024-03-18 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0048_mosabaka_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mosabaka",
            old_name="is_active",
            new_name="is_ready",
        ),
        migrations.RemoveField(
            model_name="mosabaka",
            name="ready",
        ),
    ]
